package coreframework.utils;

public enum TransType {

    //DEMO
    ADDRESS_BASE("https://demo.bookeey.com/mno/ooredooServerRequest"),
    //LIVE
    //ADDRESS_BASE("https://api.bookeey.com/mno/ooredooServerRequest"),

    PAY_TO_MERCHANT(ADDRESS_BASE.getURL()),
    LOGIN_MERCHANT(ADDRESS_BASE.getURL()),
    MERCHANT_TRAN_HISTORY_REQUEST(ADDRESS_BASE.getURL()),
    MERCHANT_REPORT_EMAIL_REQUEST(ADDRESS_BASE.getURL()),
    MERCHANT_INFO_REQUEST(ADDRESS_BASE.getURL()),
    PAY_TO_MERCHANT_COMMIT_REQUEST(ADDRESS_BASE.getURL()),
    MERCHANT_REPORT_EMAIL_RESPONSE,
    PAY_TO_MERCHANT_RESPONSE,
    MERCHANT_INFO_RESPONSE,
    LOGIN_MERCHANT_RESPONSE,
    PAY_TO_MERCHANT_COMMIT_REQUEST_RESPONSE,
    MERCHANT_TRAN_HISTORY_RESPONSE,
    LOGOUT_MERCHANT(ADDRESS_BASE.getURL()),
    LOGOUT_MERCHANT_RESPONSE,
    MERCHANT_REPORT_REQUEST(ADDRESS_BASE.getURL()),
    MERCHANT_REPORT_RESPONSE,
    OFFER_BARCODE_VALIDATION_REQUEST(ADDRESS_BASE.getURL()),
    OFFER_BARCODE_VALIDATION_RESPONSE,
    OFFER_COMMIT_REQUEST(ADDRESS_BASE.getURL()),
    OFFER_COMMIT_RESPONSE,
    GENERATE_INVOICE_REQUEST(ADDRESS_BASE.getURL()),
    GENERATE_INVOICE_RESPONSE,
    INVOICE_TRAN_RESPONSE,
    INVOICE_REMINDER_REQUEST(ADDRESS_BASE.getURL()),
    INVOICE_REMINDER_RESPONSE,
    EDIT_INVOICE_REQUEST(ADDRESS_BASE.getURL()),
    EDIT_INVOICE_RESPONSE,
    MERCHANT_OFFER_REQUEST(ADDRESS_BASE.getURL()),
    MERCHANT_OFFER_RESPONSE,
    INVOICE_EXPIRY_REQUUEST(ADDRESS_BASE.getURL()),
    INVOICE_EXPIRY_RESPONSE;

    private String server_controller_mapping;

    TransType() {
        this.server_controller_mapping = null;
    }

    TransType(String url) {
        this.server_controller_mapping = url;
    }

    public String getURL() {
        return server_controller_mapping;
    }

    public void setURL(String url) {
        this.server_controller_mapping = url;
    }

}